/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetTransactionsStreamResponse {
    #[serde(rename = "round", skip_serializing_if = "Option::is_none")]
    pub round: Option<Box<models::V1RoundTransaction>>,
    #[serde(rename = "redeem", skip_serializing_if = "Option::is_none")]
    pub redeem: Option<Box<models::V1RedeemTransaction>>,
}

impl V1GetTransactionsStreamResponse {
    pub fn new() -> V1GetTransactionsStreamResponse {
        V1GetTransactionsStreamResponse {
            round: None,
            redeem: None,
        }
    }
}
