/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetBoardingAddressResponse {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "descriptor", skip_serializing_if = "Option::is_none")]
    pub descriptor: Option<String>,
    #[serde(rename = "tapscripts", skip_serializing_if = "Option::is_none")]
    pub tapscripts: Option<Box<models::V1Tapscripts>>,
}

impl V1GetBoardingAddressResponse {
    pub fn new() -> V1GetBoardingAddressResponse {
        V1GetBoardingAddressResponse {
            address: None,
            descriptor: None,
            tapscripts: None,
        }
    }
}
