/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetInfoResponse {
    #[serde(rename = "pubkey", skip_serializing_if = "Option::is_none")]
    pub pubkey: Option<String>,
    #[serde(rename = "roundLifetime", skip_serializing_if = "Option::is_none")]
    pub round_lifetime: Option<String>,
    #[serde(
        rename = "unilateralExitDelay",
        skip_serializing_if = "Option::is_none"
    )]
    pub unilateral_exit_delay: Option<String>,
    #[serde(rename = "roundInterval", skip_serializing_if = "Option::is_none")]
    pub round_interval: Option<String>,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    #[serde(rename = "dust", skip_serializing_if = "Option::is_none")]
    pub dust: Option<String>,
    #[serde(
        rename = "boardingDescriptorTemplate",
        skip_serializing_if = "Option::is_none"
    )]
    pub boarding_descriptor_template: Option<String>,
    #[serde(
        rename = "vtxoDescriptorTemplates",
        skip_serializing_if = "Option::is_none"
    )]
    pub vtxo_descriptor_templates: Option<Vec<String>>,
    #[serde(rename = "forfeitAddress", skip_serializing_if = "Option::is_none")]
    pub forfeit_address: Option<String>,
    #[serde(rename = "marketHour", skip_serializing_if = "Option::is_none")]
    pub market_hour: Option<Box<models::V1MarketHour>>,
}

impl V1GetInfoResponse {
    pub fn new() -> V1GetInfoResponse {
        V1GetInfoResponse {
            pubkey: None,
            round_lifetime: None,
            unilateral_exit_delay: None,
            round_interval: None,
            network: None,
            dust: None,
            boarding_descriptor_template: None,
            vtxo_descriptor_templates: None,
            forfeit_address: None,
            market_hour: None,
        }
    }
}
