/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Input {
    #[serde(rename = "outpoint", skip_serializing_if = "Option::is_none")]
    pub outpoint: Option<Box<models::V1Outpoint>>,
    #[serde(rename = "descriptor", skip_serializing_if = "Option::is_none")]
    pub descriptor: Option<String>,
    #[serde(rename = "tapscripts", skip_serializing_if = "Option::is_none")]
    pub tapscripts: Option<Box<models::V1Tapscripts>>,
}

impl V1Input {
    pub fn new() -> V1Input {
        V1Input {
            outpoint: None,
            descriptor: None,
            tapscripts: None,
        }
    }
}
