/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListVtxosResponse {
    #[serde(rename = "spendableVtxos", skip_serializing_if = "Option::is_none")]
    pub spendable_vtxos: Option<Vec<models::V1Vtxo>>,
    #[serde(rename = "spentVtxos", skip_serializing_if = "Option::is_none")]
    pub spent_vtxos: Option<Vec<models::V1Vtxo>>,
}

impl V1ListVtxosResponse {
    pub fn new() -> V1ListVtxosResponse {
        V1ListVtxosResponse {
            spendable_vtxos: None,
            spent_vtxos: None,
        }
    }
}
