/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MarketHour {
    #[serde(rename = "nextStartTime", skip_serializing_if = "Option::is_none")]
    pub next_start_time: Option<String>,
    #[serde(rename = "nextEndTime", skip_serializing_if = "Option::is_none")]
    pub next_end_time: Option<String>,
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(rename = "roundInterval", skip_serializing_if = "Option::is_none")]
    pub round_interval: Option<String>,
}

impl V1MarketHour {
    pub fn new() -> V1MarketHour {
        V1MarketHour {
            next_start_time: None,
            next_end_time: None,
            period: None,
            round_interval: None,
        }
    }
}
