/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Musig2 {
    #[serde(
        rename = "cosignersPublicKeys",
        skip_serializing_if = "Option::is_none"
    )]
    pub cosigners_public_keys: Option<Vec<String>>,
    #[serde(rename = "signingAll", skip_serializing_if = "Option::is_none")]
    pub signing_all: Option<bool>,
}

impl V1Musig2 {
    pub fn new() -> V1Musig2 {
        V1Musig2 {
            cosigners_public_keys: None,
            signing_all: None,
        }
    }
}
