/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Outpoint {
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    #[serde(rename = "vout", skip_serializing_if = "Option::is_none")]
    pub vout: Option<i64>,
}

impl V1Outpoint {
    pub fn new() -> V1Outpoint {
        V1Outpoint {
            txid: None,
            vout: None,
        }
    }
}
