/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1RegisterIntentRequest {
    #[serde(rename = "bip322Signature", skip_serializing_if = "Option::is_none")]
    pub bip322_signature: Option<Box<models::V1Bip322Signature>>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<String>>,
}

impl V1RegisterIntentRequest {
    pub fn new() -> V1RegisterIntentRequest {
        V1RegisterIntentRequest {
            bip322_signature: None,
            notes: None,
        }
    }
}
