/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1RoundFinalizedEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "roundTxid", skip_serializing_if = "Option::is_none")]
    pub round_txid: Option<String>,
}

impl V1RoundFinalizedEvent {
    pub fn new() -> V1RoundFinalizedEvent {
        V1RoundFinalizedEvent {
            id: None,
            round_txid: None,
        }
    }
}
