/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1RoundStage {
    #[serde(rename = "ROUND_STAGE_UNSPECIFIED")]
    RoundStageUnspecified,
    #[serde(rename = "ROUND_STAGE_REGISTRATION")]
    RoundStageRegistration,
    #[serde(rename = "ROUND_STAGE_FINALIZATION")]
    RoundStageFinalization,
    #[serde(rename = "ROUND_STAGE_FINALIZED")]
    RoundStageFinalized,
    #[serde(rename = "ROUND_STAGE_FAILED")]
    RoundStageFailed,
}

impl std::fmt::Display for V1RoundStage {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RoundStageUnspecified => write!(f, "ROUND_STAGE_UNSPECIFIED"),
            Self::RoundStageRegistration => write!(f, "ROUND_STAGE_REGISTRATION"),
            Self::RoundStageFinalization => write!(f, "ROUND_STAGE_FINALIZATION"),
            Self::RoundStageFinalized => write!(f, "ROUND_STAGE_FINALIZED"),
            Self::RoundStageFailed => write!(f, "ROUND_STAGE_FAILED"),
        }
    }
}

impl Default for V1RoundStage {
    fn default() -> V1RoundStage {
        Self::RoundStageUnspecified
    }
}
