/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1RoundSigningNoncesGeneratedEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "treeNonces", skip_serializing_if = "Option::is_none")]
    pub tree_nonces: Option<String>,
}

impl V1RoundSigningNoncesGeneratedEvent {
    pub fn new() -> V1RoundSigningNoncesGeneratedEvent {
        V1RoundSigningNoncesGeneratedEvent {
            id: None,
            tree_nonces: None,
        }
    }
}
