/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1RegisterOutputsForNextRoundRequest {
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// List of receivers for to convert to leaves in the next VTXO tree.
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::V1Output>>,
    #[serde(rename = "musig2", skip_serializing_if = "Option::is_none")]
    pub musig2: Option<Box<models::V1Musig2>>,
}

impl V1RegisterOutputsForNextRoundRequest {
    pub fn new() -> V1RegisterOutputsForNextRoundRequest {
        V1RegisterOutputsForNextRoundRequest {
            request_id: None,
            outputs: None,
            musig2: None,
        }
    }
}
