/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1RoundSigningEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "cosignersPubkeys", skip_serializing_if = "Option::is_none")]
    pub cosigners_pubkeys: Option<Vec<String>>,
    #[serde(rename = "unsignedVtxoTree", skip_serializing_if = "Option::is_none")]
    pub unsigned_vtxo_tree: Option<Box<models::V1Tree>>,
    #[serde(rename = "unsignedRoundTx", skip_serializing_if = "Option::is_none")]
    pub unsigned_round_tx: Option<String>,
}

impl V1RoundSigningEvent {
    pub fn new() -> V1RoundSigningEvent {
        V1RoundSigningEvent {
            id: None,
            cosigners_pubkeys: None,
            unsigned_vtxo_tree: None,
            unsigned_round_tx: None,
        }
    }
}
