/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SubmitSignedForfeitTxsRequest {
    /// Forfeit txs signed by the user.
    #[serde(rename = "signedForfeitTxs", skip_serializing_if = "Option::is_none")]
    pub signed_forfeit_txs: Option<Vec<String>>,
    /// The user has to sign also the round tx if he registerd a boarding UTXO.
    #[serde(rename = "signedRoundTx", skip_serializing_if = "Option::is_none")]
    pub signed_round_tx: Option<String>,
}

impl V1SubmitSignedForfeitTxsRequest {
    pub fn new() -> V1SubmitSignedForfeitTxsRequest {
        V1SubmitSignedForfeitTxsRequest {
            signed_forfeit_txs: None,
            signed_round_tx: None,
        }
    }
}
