/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SubmitRedeemTxResponse {
    #[serde(rename = "signedRedeemTx", skip_serializing_if = "Option::is_none")]
    pub signed_redeem_tx: Option<String>,
}

impl V1SubmitRedeemTxResponse {
    pub fn new() -> V1SubmitRedeemTxResponse {
        V1SubmitRedeemTxResponse {
            signed_redeem_tx: None,
        }
    }
}
