/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SubmitRedeemTxRequest {
    #[serde(rename = "redeemTx", skip_serializing_if = "Option::is_none")]
    pub redeem_tx: Option<String>,
}

impl V1SubmitRedeemTxRequest {
    pub fn new() -> V1SubmitRedeemTxRequest {
        V1SubmitRedeemTxRequest { redeem_tx: None }
    }
}
