/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SetNostrRecipientRequest {
    #[serde(rename = "nostrRecipient", skip_serializing_if = "Option::is_none")]
    pub nostr_recipient: Option<String>,
    #[serde(rename = "vtxos", skip_serializing_if = "Option::is_none")]
    pub vtxos: Option<Vec<models::V1SignedVtxoOutpoint>>,
}

impl V1SetNostrRecipientRequest {
    pub fn new() -> V1SetNostrRecipientRequest {
        V1SetNostrRecipientRequest {
            nostr_recipient: None,
            vtxos: None,
        }
    }
}
