/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SubmitTreeSignaturesRequest {
    #[serde(rename = "roundId", skip_serializing_if = "Option::is_none")]
    pub round_id: Option<String>,
    #[serde(rename = "pubkey", skip_serializing_if = "Option::is_none")]
    pub pubkey: Option<String>,
    #[serde(rename = "treeSignatures", skip_serializing_if = "Option::is_none")]
    pub tree_signatures: Option<String>,
}

impl V1SubmitTreeSignaturesRequest {
    pub fn new() -> V1SubmitTreeSignaturesRequest {
        V1SubmitTreeSignaturesRequest {
            round_id: None,
            pubkey: None,
            tree_signatures: None,
        }
    }
}
