/*
 * ark/v1/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Vtxo {
    #[serde(rename = "outpoint", skip_serializing_if = "Option::is_none")]
    pub outpoint: Option<Box<models::V1Outpoint>>,
    #[serde(rename = "spent", skip_serializing_if = "Option::is_none")]
    pub spent: Option<bool>,
    #[serde(rename = "roundTxid", skip_serializing_if = "Option::is_none")]
    pub round_txid: Option<String>,
    #[serde(rename = "spentBy", skip_serializing_if = "Option::is_none")]
    pub spent_by: Option<String>,
    #[serde(rename = "expireAt", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<String>,
    #[serde(rename = "swept", skip_serializing_if = "Option::is_none")]
    pub swept: Option<bool>,
    #[serde(rename = "isPending", skip_serializing_if = "Option::is_none")]
    pub is_pending: Option<bool>,
    #[serde(rename = "redeemTx", skip_serializing_if = "Option::is_none")]
    pub redeem_tx: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "pubkey", skip_serializing_if = "Option::is_none")]
    pub pubkey: Option<String>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl V1Vtxo {
    pub fn new() -> V1Vtxo {
        V1Vtxo {
            outpoint: None,
            spent: None,
            round_txid: None,
            spent_by: None,
            expire_at: None,
            swept: None,
            is_pending: None,
            redeem_tx: None,
            amount: None,
            pubkey: None,
            created_at: None,
        }
    }
}
